package posting

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/ArcticWorks-Software-Company/arcticworks-codepeer/internal/domain"
)

const maxFixFiles = 10

// HandleIssueCommand processes an approve/deny comment on an analysis issue.
func (p *Poster) HandleIssueCommand(ctx context.Context, payload domain.IssueCommandPayload) error {
	issue, err := p.Store.IssueByNumber(ctx, payload.RepoID, payload.IssueNumber)
	if err != nil {
		return err
	}
	if issue == nil || issue.Status != "open" {
		p.Logger.Debug("issue command on untracked or closed issue ignored", "issue", payload.IssueNumber)
		return nil
	}
	switch strings.ToLower(strings.TrimSpace(payload.Command)) {
	case "deny":
		return p.denyIssue(ctx, payload, issue)
	case "approve":
		return p.approveIssue(ctx, payload, issue)
	default:
		return nil
	}
}

func (p *Poster) denyIssue(ctx context.Context, payload domain.IssueCommandPayload, issue *domain.IssueRecord) error {
	comment := fmt.Sprintf("Marked as resolved by @%s (`deny`).", payload.SenderLogin)
	if err := p.GitHub.AddIssueComment(ctx, payload.RepoOwner, payload.RepoName, issue.Number, comment); err != nil {
		p.Logger.Warn("deny comment failed", "issue", issue.Number, "err", err)
	}
	time.Sleep(time.Second)
	state := "closed"
	if err := p.GitHub.EditIssue(ctx, payload.RepoOwner, payload.RepoName, issue.Number, nil, &state); err != nil {
		return err
	}
	return p.Store.CloseIssue(ctx, payload.RepoID, issue.Number)
}

func (p *Poster) approveIssue(ctx context.Context, payload domain.IssueCommandPayload, issue *domain.IssueRecord) error {
	if issue.FixPRNumber > 0 {
		p.Logger.Debug("fix PR already opened for issue", "issue", issue.Number, "pr", issue.FixPRNumber)
		return nil
	}

	findings, err := p.Store.FindingsForIssue(ctx, payload.RepoID, payload.IssueNumber)
	if err != nil {
		return err
	}
	repo, err := p.Store.GetRepo(ctx, payload.RepoID)
	if err != nil {
		return err
	}
	defaultBranch := repo.DefaultBranch
	if defaultBranch == "" {
		defaultBranch, err = p.GitHub.GetDefaultBranch(ctx, payload.RepoOwner, payload.RepoName)
		if err != nil {
			return err
		}
	}

	baseSHA, err := p.GitHub.GetBranchSHA(ctx, payload.RepoOwner, payload.RepoName, defaultBranch)
	if err != nil {
		return err
	}
	treeSHA, err := p.GitHub.GetCommitTreeSHA(ctx, payload.RepoOwner, payload.RepoName, baseSHA)
	if err != nil {
		return err
	}

	var entries []domain.TreeEntry
	var changed []string
	for _, f := range findings {
		if len(entries) >= maxFixFiles {
			break
		}
		if f.Suggestion == nil || f.Suggestion.Old == "" {
			continue
		}
		content, _, err := p.GitHub.GetFileWithSHA(ctx, payload.RepoOwner, payload.RepoName, f.File, baseSHA)
		if err != nil {
			p.Logger.Warn("fix file fetch failed", "file", f.File, "err", err)
			continue
		}
		idx := strings.Index(content, f.Suggestion.Old)
		if idx < 0 {
			p.Logger.Warn("fix snippet not found in file", "file", f.File, "issue", issue.Number)
			continue
		}
		updated := strings.Replace(content, f.Suggestion.Old, f.Suggestion.New, 1)
		blobSHA, err := p.GitHub.CreateBlob(ctx, payload.RepoOwner, payload.RepoName, updated)
		if err != nil {
			return err
		}
		time.Sleep(time.Second)
		entries = append(entries, domain.TreeEntry{Path: f.File, Mode: "100644", Type: "blob", SHA: blobSHA})
		changed = append(changed, f.File)
	}

	if len(entries) == 0 {
		msg := fmt.Sprintf("Approved by @%s — no automated fix could be produced for the findings in this issue (suggestions missing or code changed since the analysis). No changes were made.", payload.SenderLogin)
		return p.GitHub.AddIssueComment(ctx, payload.RepoOwner, payload.RepoName, issue.Number, msg)
	}

	newTree, err := p.GitHub.CreateTree(ctx, payload.RepoOwner, payload.RepoName, treeSHA, entries)
	if err != nil {
		return err
	}
	commitSHA, err := p.GitHub.CreateCommit(ctx, payload.RepoOwner, payload.RepoName,
		fmt.Sprintf("CodePeer: fix issue #%d", issue.Number), newTree, []string{baseSHA})
	if err != nil {
		return err
	}
	branch := fmt.Sprintf("codepeer/fix-issue-%d", issue.Number)
	if err := p.GitHub.CreateBranch(ctx, payload.RepoOwner, payload.RepoName, branch, commitSHA); err != nil {
		return err
	}
	time.Sleep(time.Second)

	body := fmt.Sprintf("Fixes #%d\n\nAutomated fix generated by CodePeer for analysis issue #%d.\n\nFiles changed:\n- %s",
		issue.Number, issue.Number, strings.Join(changed, "\n- "))
	prNumber, err := p.GitHub.CreatePR(ctx, payload.RepoOwner, payload.RepoName,
		fmt.Sprintf("CodePeer: fix issue #%d", issue.Number), body, branch, defaultBranch)
	if err != nil {
		return err
	}
	time.Sleep(time.Second)
	comment := fmt.Sprintf("Approved by @%s — fix PR opened: #%d.", payload.SenderLogin, prNumber)
	if err := p.GitHub.AddIssueComment(ctx, payload.RepoOwner, payload.RepoName, issue.Number, comment); err != nil {
		p.Logger.Warn("approve comment failed", "issue", issue.Number, "err", err)
	}
	return p.Store.SetIssueFixPR(ctx, payload.RepoID, issue.Number, prNumber)
}
